"""Systems consolidation: hippocampus -> neocortex transfer.

This is the half of CLS that people usually skip, and the half that makes the
architecture worth building. Three things happen in a consolidation pass:

1. **Replay.** Sample the hippocampal energy landscape with Langevin dynamics
   using the exact score (see energy.py). Samples are drawn from the *smoothed*
   memory distribution, so the cortex learns the neighbourhood around each
   episode rather than memorising the episode itself.

   Replay is a *mixture* of two things, and conflating them was a real defect.
   The `episodic_ratio` share is sampled in embedding space around the stored
   embeddings: these are the true episodes, and they are the only part of the
   batch that teaches the cortex anything it did not already know. The rest is
   generated by decoding sampled latents -- pseudo-rehearsal in the sense of
   Robins (1995): the cortex is trained on its own current output, which pins
   the existing schema in place but carries no new information. Measured,
   generated replay alone left surprise on the stored memories at 1.0016x its
   value at ingestion after 150 epochs, so pruning never fired; episodic replay
   alone learned the episodes and took the schema down with it. Both are
   load-bearing, and `episodic_ratio` is where the trade-off was measured out.

2. **Interleaved training.** Train the cortex on replay mixed with new data.
   Interleaving is the mechanism that prevents catastrophic forgetting -- it is
   the entire reason biological memory bothers with a two-speed design, and
   training on new data alone would defeat the purpose of the architecture.

3. **Pruning of the now-predictable.** Re-score every stored memory through the
   updated cortex. Episodic traces the schema can now reconstruct have been
   absorbed into semantic knowledge and are dropped from the fast store.
   Evergreen records are exempt by default.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

import torch
from torch import Tensor

from .config import ConsolidationConfig, HopfieldConfig
from .energy import langevin_replay
from .hippocampus import ModernHopfieldNetwork
from .neocortex import NoveltyGate, SlowLearningNeocortex
from .records import utcnow
from .store import MemoryStore, SweepReport


@dataclass
class ConsolidationReport:
    replayed: int
    new_items: int
    epochs: int
    loss_before: float
    loss_after: float
    pruned_predicted: int
    pruned_ids: list[str] = field(default_factory=list)
    sweep: SweepReport | None = None

    @property
    def improved(self) -> bool:
        return self.loss_after < self.loss_before


class ConsolidationEngine:
    """Sleep, essentially."""

    def __init__(
        self,
        cortex: SlowLearningNeocortex,
        store: MemoryStore,
        *,
        gate: NoveltyGate | None = None,
        config: ConsolidationConfig | None = None,
        reencode_key=None,
    ) -> None:
        self.cortex = cortex
        self.store = store
        self.gate = gate
        self.config = config or ConsolidationConfig()
        self.reencode_key = reencode_key
        """Callable(MemoryRecord) -> key, used to re-index after training. Must
        be supplied whenever the key depends on the cortex."""

    # ---------------------------------------------------------------- replay

    def _latent_landscape(self) -> ModernHopfieldNetwork:
        """A Hopfield view of the memory set in *latent* space.

        Used only by the generated (pseudo-rehearsal) half of replay, which
        needs somewhere the decoder can read from -- the hippocampus proper is
        keyed on pattern-separated codes (see pattern_separation), which the
        decoder has never seen. So the energy landscape is rebuilt over the
        stored latents, carrying the same salience priors, and sampled there.

        This was once the *whole* of replay, on the reasoning that replay must
        happen in a space the cortex can read. That reasoning is wrong: the
        cortex reads embeddings, and only decoding forces the detour through
        latents. Episodic replay uses `_embedding_landscape` instead.

        Patterns are deliberately not normalised here: normalising would move
        them off the manifold the decoder was trained on. The Gibbs measure is
        then still a Gaussian mixture centred on the latents, with mixing
        weights tilted by exp(beta * ||z_i||^2 / 2) -- so Langevin sampling
        remains principled, it just favours higher-norm latents slightly. See
        the derivation in energy.py.
        """
        landscape = ModernHopfieldNetwork(
            self.store.latents().shape[-1],
            HopfieldConfig(
                beta=self.store.mhn.config.beta, normalize_patterns=False
            ),
        )
        landscape.write(self.store.latents(), self.store.mhn.log_prior.clone())
        return landscape

    def _embedding_landscape(self) -> ModernHopfieldNetwork:
        """A Hopfield view of the memory set in *embedding* space.

        This is where episodic replay has to happen. The cortex is trained on
        embeddings, so embeddings are the only space in which a replay sample
        is a target the cortex can actually be wrong about; anything routed
        through the decoder is by construction something it already emits.

        Beta here is `replay_sigma`, not the hippocampal beta -- see the
        config docstring for why the retrieval temperature is the wrong noise
        level in 256 dimensions. Patterns are left unnormalised so the replay
        targets are the true stored embeddings; the Gaussian-mixture identity
        holds at any pattern scale (see energy.py).
        """
        embeddings = self.store.embeddings()
        landscape = ModernHopfieldNetwork(
            embeddings.shape[-1],
            HopfieldConfig(
                beta=1.0 / (self.config.replay_sigma**2), normalize_patterns=False
            ),
        )
        landscape.write(embeddings, self.store.mhn.log_prior.clone())
        return landscape

    def _replay_episodic(
        self, n: int, *, generator: torch.Generator | None = None
    ) -> Tensor:
        """Hippocampal replay proper: noised samples around the true episodes."""
        if n <= 0:
            return torch.empty(0, self.cortex.config.input_dim)
        sigma = self.config.replay_sigma
        return langevin_replay(
            self._embedding_landscape(),
            n,
            steps=self.config.replay_steps,
            # ULA over a Gaussian of precision beta = 1/sigma^2 contracts by
            # (1 - beta*eta/2) per step and diverges for eta > 4/beta. At
            # sigma=0.05 that bound is 0.01, and the configured replay_step_size
            # of 0.05 is five times it -- measured, it multiplies the samples by
            # ~1300x. Capping at sigma^2 puts the contraction factor at 0.5 and
            # the stationary spread within 16% of the intended sigma.
            step_size=min(self.config.replay_step_size, sigma**2),
            generator=generator,
        )

    def _replay_generated(
        self, n: int, *, generator: torch.Generator | None = None
    ) -> Tensor:
        """Pseudo-rehearsal: latents sampled from the memory distribution and
        pushed through the VAE decoder.

        A hippocampal trace reinstating a cortical pattern, which is the
        literal mechanism the CLS account proposes -- but measured, the pattern
        it reinstates is not the episode (cosine 0.047 to the embedding it came
        from). What it actually does is hold the decoder's current function
        fixed, which is what protects the old schema.
        """
        if n <= 0:
            return torch.empty(0, self.cortex.config.input_dim)
        c = self.config
        landscape = self._latent_landscape()
        latents = langevin_replay(
            landscape,
            n,
            steps=c.replay_steps,
            # Same ULA divergence bound as the episodic half (eta > 4/beta
            # diverges), applied here too. This landscape runs at the
            # *hippocampal* beta, which is a retrieval knob -- at beta=128 the
            # bound is 0.031 against a configured step of 0.05, and samples were
            # measured blowing up 1e6x and being fed straight into cortex.fit
            # with `improved=True` reported.
            step_size=min(c.replay_step_size, 1.0 / landscape.config.beta),
            generator=generator,
        )
        with torch.no_grad():
            return self.cortex.decode(latents)

    def replay(self, n: int | None = None, *, generator: torch.Generator | None = None) -> Tensor:
        """Generate embedding-space replay samples from the hippocampus.

        A mixture of `episodic_ratio` true-episode replay and generated
        pseudo-rehearsal. See the module docstring: the first half is what lets
        consolidation actually transfer knowledge, the second is what stops it
        from overwriting the schema while doing so.
        """
        c = self.config
        n = c.replay_batch if n is None else n
        if len(self.store) == 0 or n <= 0:
            return torch.empty(0, self.cortex.config.input_dim)

        self.store.refresh_priors()
        ratio = min(max(c.episodic_ratio, 0.0), 1.0)
        n_episodic = int(round(n * ratio))
        if ratio > 0.0:
            # Round *up* to one rather than down to zero. At the default ratio
            # of 0.125 any replay batch below 4 would otherwise silently drop
            # episodic replay entirely and restore the original defect, with
            # nothing in the report to say so.
            n_episodic = min(n, max(n_episodic, 1))
        parts = [
            self._replay_episodic(n_episodic, generator=generator),
            self._replay_generated(n - n_episodic, generator=generator),
        ]
        return torch.cat([p for p in parts if p.numel() > 0], dim=0)

    # ----------------------------------------------------------- consolidate

    def consolidate(
        self,
        new_data: Tensor | None = None,
        *,
        epochs: int = 5,
        lr: float | None = None,
        now: datetime | None = None,
        generator: torch.Generator | None = None,
    ) -> ConsolidationReport:
        """One consolidation cycle: replay + interleaved training + pruning."""
        now = now or utcnow()
        c = self.config

        new_data = (
            torch.empty(0, self.cortex.config.input_dim) if new_data is None else new_data
        )
        n_new = int(new_data.shape[0])

        # Size replay so it makes up `interleave_ratio` of the batch.
        if n_new > 0 and c.interleave_ratio < 1.0:
            n_replay = int(round(n_new * c.interleave_ratio / max(1e-6, 1 - c.interleave_ratio)))
        else:
            n_replay = c.replay_batch
        replayed = self.replay(max(n_replay, 0), generator=generator)

        # Guard BEFORE the cat: torch.cat([]) raises, so the old guard below it
        # was unreachable and sleep() on a fresh system died with an opaque
        # torch error instead of returning the empty report intended here.
        parts = [t for t in (new_data, replayed) if t.numel() > 0]
        if not parts:
            return ConsolidationReport(0, 0, 0, 0.0, 0.0, 0)
        batch = torch.cat(parts, dim=0)

        with torch.no_grad():
            loss_before = float(self.cortex.elbo_loss(batch)[0])
        self.cortex.fit(batch, epochs=epochs, lr=lr)
        with torch.no_grad():
            loss_after = float(self.cortex.elbo_loss(batch)[0])

        # Training moved the encoder, so every latent-derived key is now stale.
        # Without this the read path would encode queries with the new cortex
        # while the hippocampus still held old-cortex keys (measured cosine
        # 0.39 for the same text across one consolidation pass).
        if self.reencode_key is not None:
            self.store.reindex(self.reencode_key)

        pruned = self.prune_predicted(now=now) if c.prune_predicted else []
        sweep = self.store.sweep(now)

        return ConsolidationReport(
            replayed=int(replayed.shape[0]),
            new_items=n_new,
            epochs=epochs,
            loss_before=loss_before,
            loss_after=loss_after,
            pruned_predicted=len(pruned),
            pruned_ids=pruned,
            sweep=sweep,
        )

    # ----------------------------------------------------------------- prune

    def prune_predicted(
        self,
        *,
        threshold: float | None = None,
        now: datetime | None = None,
        mode: str | None = None,
    ) -> list[str]:
        """Drop episodic memories the cortex has demonstrably absorbed.

        This is the closing of the loop: the hippocampus is a staging area, and
        anything the schema has learned should not keep occupying it.

        The criterion is a *relative drop* against the item's surprise at
        ingestion: prune when `surprise_now < relative_drop * novelty_at_write`.
        It deliberately does NOT default to the novelty gate's threshold. That
        threshold is a quantile of the live ingestion window, which drifts
        upward as new items arrive, so comparing against it prunes memories on
        pure quantile drift -- measured removing 1 of 4 memories on a system
        whose cortex had not been trained at all since those memories were
        written. A relative drop can only fire if this cortex actually improved
        on this item.

        Pass an absolute `threshold` to override (still combined with the
        relative test, so an unchanged cortex cannot trigger a prune).

        This fires only if replay carries real episodes. Against decoder-only
        replay the criterion was correct and inert: surprise on the stored
        memories sat at 1.0016x its ingestion value after a 150-epoch pass, so
        nothing was ever released. See `ConsolidationConfig.episodic_ratio`.
        """
        if len(self.store) == 0:
            return []

        mode = mode or (self.gate.config.mode if self.gate else "recon")
        embeddings = self.store.embeddings()
        scores = self.cortex.surprise(embeddings, mode)

        doomed = []
        for record, s in zip(self.store.records, scores.tolist()):
            if record.is_evergreen and self.config.protect_evergreen:
                continue
            learned = record.novelty > 0 and s < self.config.relative_drop * record.novelty
            if threshold is not None:
                learned = learned and s <= threshold
            if learned:
                doomed.append(record.id)
        removed = self.store.remove(doomed)
        self.store.refresh_priors(now)
        return removed

    # ------------------------------------------------------------ diagnostics

    def predictability(self) -> dict:
        """Per-record surprise under the current cortex -- shows which memories
        are on their way to being consolidated away."""
        if len(self.store) == 0:
            return {}
        mode = self.gate.config.mode if self.gate else "recon"
        scores = self.cortex.surprise(self.store.embeddings(), mode)
        return {r.id: float(s) for r, s in zip(self.store.records, scores.tolist())}

    def drop_ratios(self) -> dict:
        """Per-record `surprise_now / novelty_at_ingestion`.

        The quantity `prune_predicted` actually thresholds, exposed on its own
        because the prune count is a step function and hides progress: a pass
        that moves the median from 1.00 to 0.65 has consolidated a great deal
        while releasing nothing. Records ingested with novelty 0 (the evergreen
        bypass can store an unsurprising rule) report inf, since a relative
        drop is undefined for them and they can never be pruned this way.
        """
        if len(self.store) == 0:
            return {}
        mode = self.gate.config.mode if self.gate else "recon"
        scores = self.cortex.surprise(self.store.embeddings(), mode)
        return {
            r.id: (float(s) / r.novelty if r.novelty > 0 else float("inf"))
            for r, s in zip(self.store.records, scores.tolist())
        }
